model_name_or_path: deepseek-ai/deepseek-coder-6.7b-instruct
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
dataset: cpp2cuda_codepair_train
template: deepseek
cutoff_len: 4096
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
output_dir: /mnt/data2/cpp2cuda_models/deepseek-coder-6_7b-sft-lora
run_name: cpp2cuda_deepseek-coder-6_7b-finetune-lora
